apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.remote.name }}
  namespace: {{ .Values.pvc.remote.namespace }}
spec:
  {{- if .Values.local.enabled }}
  storageClassName: {{ .Values.local.storageClassName | quote }}
  {{- else }}
  storageClassName: {{ .Values.pvc.remote.storageClassName | quote }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
{{- if .Values.pvc.rasters.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.rasters.name }}
  namespace: {{ .Values.pvc.remote.namespace }}
spec:
  storageClassName: {{ .Values.pvc.remote.storageClassName | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{{- end -}}

{{- if .Values.pvc.netcdf.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.netcdf.name }}
  namespace: {{ .Values.pvc.remote.namespace }}
spec:
  storageClassName: {{ .Values.pvc.remote.storageClassName | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
{{- end -}}

