apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: "{{ .Values.cronjob.repository }}:{{ .Values.cronjob.tag }}"
            imagePullPolicy: {{ .Values.cronjob.pullPolicy }}
            command: ["sh", "run.sh"]
            env:
                - name: POSTGRES_HOST
                  value: {{ include "postgres.fullname" . }}
                - name: POSTGRES_PORT
                  value: {{ .Values.service.port | quote }}
                - name: POSTGRES_USER
                  value: {{ .Values.postgresqlUsername }}
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "postgres.fullname" . }}
                      key: postgres-password
                - name: S3_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "postgres.fullname" . }}
                      key: aws-access-key-id
                - name: S3_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "postgres.fullname" . }}
                      key: aws-secret-access-key
                - name: S3_BUCKET
                  value: {{ .Values.s3bucket }}
                - name: S3_REGION
                  value: eu-west-1
                - name: S3_URL
                  value: {{ .Values.s3url }}
                - name: NAMESPACE
                  value: {{ .Values.namespace }}
          restartPolicy: OnFailure
