apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdatadefault
  namespace: {{ .Values.pv.remote.namespace }}
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
