apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdatadefault
  namespace: {{ .Values.pv.remote.namespace }}
spec:
  storageClassName: {{ .Values.pv.remote.storageClassName | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
