apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresqlPassword | b64enc }}
  aws-access-key-id: {{ .Values.awsAccessKeyId | b64enc }}
  aws-secret-access-key: {{ .Values.awsSecretAccessKey | b64enc }}
