apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgresql.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresqlPassword | b64enc }}
