apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
  serviceName: "postgres"
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "postgres.selectorLabels" . | nindent 8 }}
    spec:

      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP

          volumeMounts:
            - mountPath: /var/lib/postgresql/data/pgdata 
              name: postgresdatadefault
              subPath: postgres-db

        env:
          - name: POSTGRES_USER
            value: "geoserver"
          - name: POSTGRES_PASSWORD
            value: "supersecret"
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata

  volumeClaimTemplates:
    - metadata:
        name: postgresdatadefault
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi