apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.remote.name }}
  namespace: {{ .Values.pvc.remote.namespace }}
spec:
  storageClassName: {{ .Values.pvc.remote.storageClassName | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

