apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geoserver-chart.fullname" . }}
  labels:
    {{- include "geoserver-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "geoserver-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "geoserver-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - mountPath: "/geoserver_data/data"
            name:  {{ .Values.pv.name }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
      volumes:
        - name: {{ .Values.pv.name }}
          persistentVolumeClaim:
            claimName:  {{ .Values.pv.name }}