apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" .Release.Name "terriamap-config-server" | trunc 63 | trimSuffix "-" | quote }}
  labels:
    {{- include "terria.labels" . | nindent 4 }}
data:
  serverconfig.json: |-
      {
        "port": {{ .Values.service.port }},
        "allowProxyFor": ["{{ .Release.Namespace }}-geoserver:8080"],
        "blacklistedAddresses": [],
        "proxyAuth": {
          "{{ .Release.Namespace }}-geoserver:8080": {
              "authorization": "Basic {{ .Values.geoserverCredentials | b64enc }}"
          }
        }
      }