apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "terria.fullname" . }}
  labels:
    {{- include "terria.labels" . | nindent 4 }}
data:
  config.json: '{{ toJson .Values.clientConfig | indent 2 }}'