apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" .Release.Name "terriamap-init-config" | trunc 63 | trimSuffix "-" | quote }}
  labels:
    {{- include "terria.labels" . | nindent 4 }}
data:
  terria.json: |-
    {
        "homeCamera": {
            "north": {{ default 5 .Values.initConfig.homeCamera.north }},
            "east": {{ default 177 .Values.initConfig.homeCamera.east }},
            "south": {{ default -24 .Values.initConfig.homeCamera.south }},
            "west": {{ default 152 .Values.initConfig.homeCamera.west }}
        },
        "catalog": [
            {{- $lenCatalog := len .Values.initConfig.geoserverWorkspaces -}}
            {{- range  $i, $e := .Values.initConfig.geoserverWorkspaces }}
            {
                "name": "DRR",
                "type": "wfs-getCapabilities",
                "description": "This group contains vector data for Solomon",
                "url": "http://{{ $.Release.Namespace }}-geoserver:8080/geoserver/{{ . }}/ows?service=wfs&version=2.0.0&request=GetCapabilities"
            }{{- if ne $i (sub $lenCatalog 1) -}},{{- end -}}
            {{- end }}
        ]
    }

# do for loop