{{- if .Values.authentication.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terria.fullname" . }}
  labels:
    {{- include "terria.labels" . | nindent 4 }}
stringData:
  {{ .Values.authentication.authData | nindent 2 }}
type: Opaque
{{- end }}
