apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thredds.fullname" . }}
  labels:
    {{- include "thredds.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "thredds.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "thredds.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "thredds.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: init-{{ .Chart.Name }}
        image: "davidedelerma/init-thredds:0.2"
        volumeMounts:
        - name: {{ .Values.pvc.name }}
          mountPath: "/thredds-content"
        command: ["mv", "thredds", "thredds-content"]
      volumes:
          - name: {{ .Values.pvc.name }}
            persistentVolumeClaim:
              claimName: {{ .Values.pvc.name }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: "/usr/local/tomcat/content"
            name:  {{ .Values.pvc.name }}
            
          ports:
            - name: liveness-port
              containerPort: {{ .Values.service.port }}
              hostPort: {{ .Values.service.port }}

          livenessProbe:
            httpGet:
              path: /thredds/catalog/catalog.html
              port: liveness-port
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /thredds/catalog/catalog.html
              port: liveness-port
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
