apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thredds.fullname" . }}
  labels:
    {{- include "thredds.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "thredds.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "thredds.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "thredds.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: init-{{ .Chart.Name }}
        image: "davidedelerma/init-thredds:0.3"
        volumeMounts:
        - name: {{ .Values.pvc.configuration.name }}
          mountPath: "/thredds-content"
        command: ["mv", "thredds", "thredds-content"]
      volumes:
          - name: {{ .Values.pvc.configuration.name }}
            persistentVolumeClaim:
              claimName: {{ .Values.pvc.configuration.name }}
          - name: {{ .Values.pvc.netcdfMontlyYearly.name }}
            persistentVolumeClaim:
              claimName: {{ .Values.pvc.netcdfMontlyYearly.name }}
          - name: {{ .Values.pvc.netcdfDaily1.name }}
            persistentVolumeClaim:
              claimName: {{ .Values.pvc.netcdfDaily1.name }}
          - name: {{ .Values.pvc.netcdfDaily2.name }}
            persistentVolumeClaim:
              claimName: {{ .Values.pvc.netcdfDaily2.name }}
      containers:
        - name: {{ .Chart.Name }}-sidecar
          image: "{{ .Values.sidecar.image.repository }}:{{ .Values.sidecar.image.tag }}"
          imagePullPolicy: {{ .Values.sidecar.image.pullPolicy }}
          volumeMounts:
          - mountPath: "/usr/local/monthly-yearly-data"
            name:  {{ .Values.pvc.netcdfMontlyYearly.name }}
          - mountPath: "/usr/local/daily-1-data"
            name:  {{ .Values.pvc.netcdfDaily1.name }}
          - mountPath: "/usr/local/daily-2-data"
            name:  {{ .Values.pvc.netcdfDaily2.name }}
          env:
          - name: AWS_ACCESS_KEY_ID
            value : 307282071fcfef61a70d
          - name: AWS_SECRET_ACCESS_KEY
            value: y+w07ahZjvaaF6TNy8uhr82xj2ksy7nLhknTmIGW
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: "/usr/local/tomcat/content"
            name:  {{ .Values.pvc.configuration.name }}
          - mountPath: "/usr/local/monthly-yearly-data"
            name:  {{ .Values.pvc.netcdfMontlyYearly.name }}
          - mountPath: "/usr/local/daily-1-data"
            name:  {{ .Values.pvc.netcdfDaily1.name }}
          - mountPath: "/usr/local/daily-2-data"
            name:  {{ .Values.pvc.netcdfDaily2.name }}
          ports:
            - name: liveness-port
              containerPort: {{ .Values.service.port }}
              hostPort: {{ .Values.service.port }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /thredds/catalog.html
              port: liveness-port
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /thredds/catalog.html
              port: liveness-port
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
