apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.configuration.name }}
  namespace: {{ .Values.pvc.configuration.namespace }}
spec:
  storageClassName: {{ .Values.pvc.configuration.storageClassName | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.netcdfMontlyYearly.name }}
  namespace: {{ .Values.pvc.netcdfMontlyYearly.namespace }}
spec:
  storageClassName: {{ .Values.pvc.netcdfMontlyYearly.storageClassName | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.netcdfDaily1.name }}
  namespace: {{ .Values.pvc.netcdfDaily1.namespace }}
spec:
  storageClassName: {{ .Values.pvc.netcdfDaily1.storageClassName | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.netcdfDaily2.name }}
  namespace: {{ .Values.pvc.netcdfDaily2.namespace }}
spec:
  storageClassName: {{ .Values.pvc.netcdfDaily2.storageClassName | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi