name: Validation

on:
  pull_request:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Run chart-testing (lint)
        id: lint
        # Support for Helm 2 is on branch dev-v2.
        uses: helm/chart-testing-action@dev-v2
        with:
          command: lint

  validation:
    runs-on: ubuntu-latest
    needs:
      - linting
    steps:
      - uses: actions/checkout@v2
      - name: Kubernetes toolset
        uses: desaintmartin/helm-kubeval-action@master
        with:
          path: ./helm-charts
